<!doctype html>
<html lang="en">
<head>
    <title>KEEP</title>
    <link rel="icon" href="../assets/images/icon.png" type="image/x-icon">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- external css -->
    <link rel="stylesheet" href="css/terms.css">
    <!-- Bootstrap CSS -->
    <link href="../bootstrap-5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Fontawesome -->
    <link href="../assets/fontawesome-free-6.0.0-web/css/fontawesome.css" rel="stylesheet">
    <link href="../assets/fontawesome-free-6.0.0-web/css/brands.css" rel="stylesheet">
    <link href="../assets/fontawesome-free-6.0.0-web/css/solid.css" rel="stylesheet">
</head>
<body>

<div class="container">
<section id="section_1" class="text-center">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a class="bread_item" href="../index.php">Home</a></li>
            <li class="breadcrumb-item"><a class="bread_item" href="LogIn.php">Sign Up</a></li>
            <li class="breadcrumb-item"><a class="bread_item" id="privacyBtn" href="#section_3">Privacy Policy</a></li>
            <li class="breadcrumb-item"><a class="bread_item" id="termsBtn" href="#section_4">Terms and Conditions</a></li>
        </ol>
    </nav>
    <h1 class="text-center">
        <img src="../assets/images/icon.png" class="float-left img-fluid" width="100" height="100" > 
        K E E P
    </h1>
    <h2 class="text-center">Terms and Conditions and Privacy Policy</h2>
</section>

<section id="section_2_privacy">
    <div class="hr"></div>
    <h5><strong>Privacy Policy</strong></h5></br>
    <h6>Last updated: <i>March 05, 2022</i></h6>
    <p>
    This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
    We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Template.
    </p>
    <div class="hr"></div>
</section>

<!-- privacy policy -->
<section id="section_3">
    <h2 class="title">Privacy Policy</h2>
    <h4>Interpretation and Definitions</h4>
    <hr>
    <h5>Interpretation</h5>
    <p>
    The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
    </p>
    </br>
    <h5>Definitions</h5>
    <p>For the purposes of this Privacy Policy:</p>
    <ul class="nobullet_list">
        <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
        <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement)  refers to KEEP.</li>
        <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
        <li><strong>Country </strong>refers to: Philippines</li>
        <li><strong>Device </strong>means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
        <li><strong>Personal Data </strong>is any information that relates to an identified or identifiable individual.</li>
        <li><strong>Service </strong>refers to the Website.</li>
        <li><strong>Service Provider </strong>means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
        <li><strong>Third-party Social Media Service </strong>refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
        <li><strong>Usage Data </strong>refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
        <li><strong>Website </strong>refers to KEEP, accessible from <a href="https://keepcs.000webhostapp.com/">https://keepcs.000webhostapp.com/</a> </li>
        <li><strong>You </strong>means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
    </ul>
    </br>
    <h4>Collecting and Using Your Personal Data</h4>
    <hr>
    <h5>Types of Data Collected</h5>
    </br>
    <h6><strong>Personal Data</strong></h6>
    <p>While using Our Service, We may ask You to provide to Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
    <ul>
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
        <li>Address, State, Province, ZIP/Postal code, City</li>
        <li>Usage Data</li>
        <li>Educational background</li>
        <li>Career background</li>
    </ul>
    </br>
    <h6><strong>Usage Data</strong></h6>
    <p>Usage Data is collected automatically when using the Service.</br>
    Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</br>
    We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
    </br>
    <h6><strong>Tracking Technologies and Cookies</strong></h6>
    <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
    <ul>
        <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
        <li><strong>Flash Cookies.</strong> Certain features of our Service may use local stored objects (or Flash Cookies) to collect and store information about Your preferences or Your activity on our Service. Flash Cookies are not managed by the same browser settings as those used for Browser Cookies. For more information on how You can delete Flash Cookies, please read "Where can I change the settings for disabling, or deleting local shared objects?" available at https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_</li>
        <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
    </ul>
    <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. You can learn more about cookies here: Cookies by TermsFeed Generator.</p>
    <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
    <ul class="nobullet_list">
        <li><strong>Necessary / Essential Cookies</strong></br>
            <strong>Type:</strong> Session Cookies</br>
            <strong>Administered by:</strong> Us</br>
            <strong>Purpose:</strong> These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.
        </li></br>
        <li><strong>Cookies Policy / Notice Acceptance Cookies</strong></br>
            <strong>Type:</strong> Persistent Cookies</br>
            <strong>Administered by:</strong> Us</br>
            <strong>Purpose:</strong> These Cookies identify if users have accepted the use of cookies on the Website.
        </li></br>
        <li><strong>Functionality Cookies</strong></br>
            <strong>Type:</strong> Persistent Cookies</br>
            <strong>Administered by:</strong> Us</br>
            <strong>Purpose:</strong> These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.
        </li>
    </ul>
    <p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>
    </br>
    <h6><strong>Use of Your Personal Data</strong></h6>
    <p>The Company may use Personal Data for the following purposes:</p>
    <ul class="nobullet_list">
        <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
        <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
        <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
        <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
        <li><strong>To provide You</strong> with updated, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
        <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
        <li><strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</li>
        <li><strong>For other purposes:</strong> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, marketing and your experience.</li>
    </ul>
    <p>We may share Your personal information in the following situations:</p>
    <ul>
        <li><strong>With Service Providers:</strong> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</li>
        <li><strong>For business transfers:</strong> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
        <li><strong>With Affiliates:</strong> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
        <li><strong>With business partners:</strong> We may share Your information with Our business partners to offer You certain products, services or promotions.</li>
        <li><strong>With other users:</strong> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.</li>
        <li><strong>With Your consent:</strong> We may disclose Your personal information for any other purpose with Your consent.</li>
    </ul>
    </br>
    <h6><strong>Retention of Your Personal Data</strong></h6>
    <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
    <p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>
    </br>
    <h6><strong>Transfer of Your Personal Data</strong></h6>
    <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
    <p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
    <p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
    </br>
    <h6><strong>Disclosure of Your Personal Data</strong></h6>
    <p><strong>Business Transactions</strong>
    If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
    </p>
    <p><strong>Law enforcement</strong>
Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
    </p>
    <p><strong>Other legal requirements</strong>
    The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
    </p>
    <ul>
        <li>Comply with a legal obligation</li>
        <li>Protect and defend the rights or property of the Company</li>
        <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
        <li>Protect the personal safety of Users of the Service or the public</li>
        <li>Protect against legal liability</li>
    </ul>
    <p><strong>Security of Your Personal Data</strong>
    The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
    </p>

    </br>
    <h4>Collecting and Using Your Personal Data</h4>
    <hr>
    <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
    <p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>

    </br>
    <h4>Links to Other Websites</h4>
    <hr>
    <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
    <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
    
    </br>
    <h4>Links to Other Websites</h4>
    <hr>
    <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
    <p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>
    <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
    
    </br>
    <h4>Contact Us</h4>
    <hr>
    <p>If you have any questions about this Privacy Policy, You can contact us at: <strong><i>keep.webpage@gmail.com</i></strong></p>
</section>
<!-- Terms and Conditions -->
<section id="section_2_terms">
    <div class="hr"></div>
    <h5><strong>Terms and Conditions</strong></h5></br>
    <h6>Last updated: <i>March 08, 2022</i></h6>
    <p>Welcome to KEEP  Terms and Conditions! We appreciate you for giving time to read this. Thank you for choosing to use our services.</p>
    <p>Important legal terms and conditions that apply to anyone who visits our website or utilizes our services are stated below. These terms are required to safeguard both you and us, as well as to enable and improve our services for everyone. Because KEEP provides features, some of the terms listed below may not apply to the services you use.</p>
    <p>We acknowledge that reading legal terms can be tedious, so we've made an effort to make it more pleasant. You are invited to contact us at keep.webpage@gmail.com if you have any thoughts on how we can enhance them.</p>
    <div class="hr"></div>
</section>

<section id="section_4">
    <h2 class="title">Terms and Conditions</h2>
    <h4>Your KEEP Account</h4>
    <hr>
    <p>If you create an account on the Website, you are responsible for maintaining the security of your account, and you are fully responsible for all activities that occur under the account and any other actions taken in connection with the account. You agree to provide and maintain accurate, current and complete information, including your contact information for notices and other communications from us. You may not use false or misleading information in connection to your account, or trade on the name or reputation of others, and KEEP may change or remove any information that it considers inappropriate or unlawful, or otherwise likely to expose KEEP to claims of third parties. You agree that we may take steps to verify the accuracy of information you have provided to us.</p>
    <p>You are responsible for taking reasonable steps to maintain the confidentiality of your username and password. You must immediately notify KEEP of any unauthorized uses of your information, your account or any other security breaches. KEEP will not be liable for any acts or omissions by you, including any damages of any kind incurred as a result of such acts or omissions.</p>
    </br>
    <h4>Responsibility of Users of the Website, Products, and/or Services</h4>
    <hr>
    <p>Your access to, and all of your use of the Website, Products, and/or Services must be lawful and must be in compliance with these Terms, and any other agreement between you and KEEP. When accessing or using the Website, Products, and/or Services, you must behave in a civil and respectful manner at all times. We specifically prohibit any use of the Website, Products, and/or Services, and you agree not to use the Website, for any of the following:</p>
    <ul>
        <li>Engaging in conduct that would constitute a criminal offense, giving rise to civil liability or otherwise violate any city, state, national or international law or regulation that would fail to comply with accepted internet protocol;</li>
        <li>Communicating, transmitting, or posting material that is copyrighted or otherwise owned by a third party unless you are the copyright owner or have the permission of the owner to post it;</li>
        <li>Communicating, transmitting, or posting material that reveals trade secrets, unless you own them or have the permission of the owner;</li>
        <li>Communicating, transmitting, or posting material that infringes on any other intellectual property, privacy or publicity right of another;</li>
        <li>Attempting to interfere in any way with the Website, or our networks or network security, or attempting to use our Website to gain unauthorized access to any other computer system;</li>
        <li>Accessing data not intended for you, or logging on to a server or account, which you are not authorized to access;</li>
        <li>Attempting to probe, scan or test the vulnerability of a system or network or to breach security or authentication measures without proper authorization (or succeeding in such an attempt);</li>
        <li>Attempting to interfere or interfering with the operation of the Website, Products, and/or Services, or our provision of Services to any other users of the Website, our hosting provider or our network, including, without limitation, via means of submitting a virus to the Website, overloading, “flooding”, “mail bombing” or “crashing” the Website.</li>
    </ul>
    <p>In addition, if you operate an account, contribute to an account, post material to the Website, post links on the Website, or otherwise make material available by means of the Website (any such material, "Content"), you are solely responsible for the content of, and any harm and damages resulting from that Content. That is the case regardless of whether the Content in question constitutes text, graphics, an audio file, or computer software. By making Content available, you represent and warrant that:</p>
    <ul>
        <li>the downloading, copying and use of the Content will not infringe the proprietary rights, including but not limited to the copyright, patent, trademark or trade secret rights, of any third party;</li>
        <li>the Content does not contain or install any viruses, worms, malware, Trojan horses or other harmful or destructive content;</li>
        <li>the Content is not spam, and does not contain unethical or unwanted commercial content designed to drive traffic to third party sites or boost the search engine rankings of third party sites, or to further unethical or unlawful acts (such as phishing) or mislead recipients as to the source of the material (such as spoofing);</li>
        <li>The Content is not obscene, libelous, hateful or racially or ethnically objectionable, and does not violate the privacy or publicity rights of any third party.</li>
    </ul>
    <p>If you delete Content, KEEP will use reasonable efforts to remove it from the Website and our servers, but you acknowledge that caching or references to the Content may not be made unavailable to the public immediately.</p>
    <p>You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content. KEEP shall take reasonable precautions to prevent the transmission of harmful content from its technology systems to your technology systems.</p>
    <p>KEEP disclaims any liability for any harm or damages resulting from your access or use of the Website, Products, and/or Services, or access or use of non-KEEP websites.</p>
    <p>KEEP has the right (though not the obligation) to </p>
    <ul class="roman_bullet">
        <li>refuse or remove any Content that, in KEEP’s reasonable opinion, violates any KEEP policy or is in any way harmful or objectionable, or </li>
        <li>terminates or denies access to and use of the Website, Products, and/or Services, to any person for any reason, in KEEP’s sole discretion.</li>
    </ul>

    </br>
    <h4>Use of Third Party Content and Materials</h4>
    <hr>
    <p>KEEP has not reviewed, and cannot review, all of the material, including computer software, posted to the Website, and cannot therefore be responsible for that material’s content, use or effects. By operating the Website, KEEP does not represent or imply that it endorses the material there posted, or that it believes such material to be accurate, useful or non-harmful. The Website may contain content that is offensive, indecent, or otherwise objectionable, as well as content containing technical inaccuracies, typographical mistakes, and other errors. The Website may also contain material that violates the privacy or publicity rights, or infringes the intellectual property and other proprietary rights, of third parties, or the downloading, copying or use of which is subject to additional terms and conditions, stated or unstate. KEEP disclaims any responsibility for any harm and/or damages resulting from the use or downloading of postings of other parties on the website.</p>

    </br>
    <h4>Content Posted on Other Websites</h4>
    <hr>
    <p>We have not reviewed, and cannot review, all of the material, including computer software, made available through the websites and webpages to which KEEP.com links, and that link to KEEP.com. KEEP does not have any control over those non-KEEP websites and webpages, and is not responsible for their contents or their use. By linking to a non-KEEP website or webpage, KEEP does not represent or imply that it endorses such website or webpage.</p>
    
    </br>
    <h4>Copyright Infringement</h4>
    <hr>
    <p>As KEEP requires others to respect its intellectual property rights, it respects the intellectual property rights of others. If you believe that material located on or linked to by the Website violates your copyright, you are encouraged to notify KEEP. KEEP will, as it is able, respond to all such notices, including as required or appropriate by removing the infringing material or disabling all links to the infringing material. In order to bring infringing material to our attention, you must provide our DMCA Agent with the following information: </p>
    <ul class="roman_bullet">
        <li>an electronic or physical signature of the person authorized to act on behalf of the owner of the copyrighted work; </li>
        <li>an identification of the copyrighted work and the location on the Website of the allegedly infringing work; </li>
        <li>a written statement that you have a good faith belief that the disputed use is not authorized by the owner, its agent or the law; </li>
        <li>your name and contact information, including telephone number and email address; and </li>
        <li>a statement by you that the above information in your notice is accurate and, under penalty of perjury, that you are the copyright owner or authorized to act on the copyright owner’s behalf.</li>
    </ul>
    <p>In the case of a user who may infringe or repeatedly infringes upon the copyrights or other intellectual property rights of KEEP or others, KEEP may, in its discretion, terminate or deny access to and use of the Website, Products, and/or Services. In the case of such termination, KEEP will have no obligation to any person in respect of any such termination.</p>
    
    </br>
    <h4>Trademarks</h4>
    <hr>
    <p>KEEP, the KEEP logo, and all other trademarks, service marks, graphics and logos used in connection with the Website, Products, and Services, are trademarks or registered trademarks of KEEP. Other trademarks, service marks, graphics and logos used in connection with the Website, Products, and Services, may be the trademarks of other third parties in which case such license is for the exclusive benefit and use of us unless otherwise stated, or may be the property of their respective owners. Your use of the Website grants you no right or license to reproduce or otherwise use any KEEP or third party trademarks. Likewise, you grant no right or license to reproduce or otherwise use any of your trademarks, service marks, graphics and/or logos, unless expressly authorized by you.</p>
    
    </br>
    <h4>Termination</h4>
    <hr>
    <p>You may terminate your agreement and close your account with KEEP at any time,  by deleting your account in KEEP. KEEP may terminate its relationship with you, or may terminate or suspend the accessibility to the E-portfolio, Products, and/or Services at any time, including the use of any software, </p>
    <ul class="roman_bullet">
        <li>if you breach these Terms and/or any other agreement with KEEP; </li>
        <li>if KEEP reasonably suspects that you are using the Website, Products, and/or Services to breach the law or infringe third party rights;</li>
        <li>if KEEP reasonably suspects that you are trying to unfairly exploit or misuse KEEP’s policies; </li>
        <li>if KEEP reasonably suspects that you are using the Website, Products, and/or Services fraudulently, or that Products or Services provided to you are being used by a third party fraudulently; </li>
        <li>if you fail to pay any amounts due to KEEP; </li>
        <li>you violate any applicable law or regulation. Upon termination of your KEEP account for the above reasons, there will be no refund of fees and you will be denied access to the Website, Products and/or the Services, including all of its data.</li>
    </ul>
    <p>KEEP may terminate any agreement and access to your account, if the Services or any part thereof, are no longer legally available in your jurisdiction, or are no longer commercially viable, at KEEP’s sole discretion. In case of termination or closing of your account by you because of a material breach by KEEP, without any default by you, or in case of a force majeure on the side of KEEP. If you believe that KEEP has failed to perform or the Services are defective, you must notify KEEP in writing and allow fourteen (14) days for KEEP to cure the defect. If KEEP cures the defect within this fixing period, KEEP will not be in default and cannot be held liable for any damages and/or losses in connection to such default. If KEEP has not fixed the defect within this fixing period, you may terminate the subscription with immediate effect or delete your account, upon written notice to KEEP.</p>
    
    </br>
    <h4>Changes</h4>
    <hr>
    <p>The configurations and specifications of the Website, including without limitation all content there available, the Products, and the Services may be amended and/or updated from time to time, at the sole discretion of KEEP. You are bound by any such changes or updates, unless such changes materially diminish the functionality and value of the Website, Products and/or Services.</p>
    
    </br>
    <h4>Limitation of Liability of KEEP</h4>
    <hr>
    <p>Under no circumstances shall any party, its subsidiaries and affiliates, their respective directors, officers, employees or agents, and other representatives, be liable for any indirect, consequential, incidental, special, or punitive damages, including but not limited to lost profits and business interruption, whether in contract or in tort, including negligence, arising in any way from the use of the Website, Products, Services, and/or the Contents thereof, or of any hyperlinked website even if such party is expressly advised of the possibility of such damages. With the exception of damages related to legally proven or admitted intellectual property infringement caused by Products and/or Services as delivered by a party without any third party content, in no event shall a party’s liability exceed the total sums received by KEEP from you during the twelve (12) month period immediately prior to the date the damages first occurred.</p>
    
    </br>
    <h4>Your Representations and Warranties</h4>
    <hr>
    <p>You represent and warrant that your use of the Website, Products, and/or Services will be in accordance with any agreement between you and KEEP, the KEEP Privacy Policy, these Terms, and with any applicable laws and regulations, including without limitation any local laws or regulations in your country, state, city, or other governmental area, regarding online conduct and acceptable content, and including all applicable laws regarding the transmission of technical data exported from the country in which you reside, and with any other applicable policy or terms and conditions.</p>
</section>
</div>

<!-- To Top -->
<button onclick="topFunction()" id="toTop" title="Go to top"><i class="fa fa-chevron-up"></i></button>


<script>
// TO TOP
//Get the button
var mybutton = document.getElementById("toTop");

// When the user scrolls down 20px from the top of the document, show the button
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
    if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
        mybutton.style.display = "block";
    } else {
        mybutton.style.display = "none";
    }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
    document.body.scrollTop = 0;
    document.documentElement.scrollTop = 0;
}
</script>
<!-- Optional JavaScript; choose one of the two! -->
<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="../bootstrap-5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
-->
</body>
</html>